
server:
  port: 8082
spring:
  cloud:
    discovery:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: GROOMER-MSG
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  datasource:
    url: jdbc:postgresql://localhost:5434/msg_db
    username: postgres
    password: postgres
  rabbitmq:
    port: 5672
    username: ENC(GKtUVhqiH5zVM/suBe6CuQ==)
    password: ENC(GKtUVhqiH5zVM/suBe6CuQ==)
    registrationQueue: q.user_registration
    registrationRoutingKey: k.registration
    appointmentConfirmationQueue: q.appointment_confirmation
    confirmationRoutingKey: k.confirmation
    appointmentCancellationQueue: q.appointment_cancellation
    cancellationRoutingKey: k.cancellation
    exchangeName: x.message_exchange
  mail:
    host: smtp.poczta.onet.pl
    port: 587
    username: ENC(h3tFpUWHffT2vQqVFk94ndnku10ItZoWT3p4baYxxIo=)
    password: ENC(AsOORStniO5XEDKVo/WKATz7Ed3qPxJB)
    smtp:
      auth: true
      starttls:
        enable: true
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path: /swagger-ui-custom.html
jasypt:
  encryptor:
        password: MSN_04_Sazabi
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
